# Generated by Django 5.1.2 on 2024-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0002_alter_userprofile_options_meter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=30),
        ),
    ]
