# Generated by Django 5.1.2 on 2024-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0003_alter_meter_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
