# Generated by Django 5.1.2 on 2024-11-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0007_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
