# Generated by Django 5.1.2 on 2024-11-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0007_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
