# Generated by Django 5.1.2 on 2024-11-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0010_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
