# Generated by Django 5.1.2 on 2024-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0016_userprofile_password_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('staff', 'staff'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
