# Generated by Django 5.1.2 on 2025-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0020_remove_userprofile_user_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='meter',
            name='remaining_energy',
        ),
        migrations.AddField(
            model_name='meter',
            name='address',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter',
            name='national_id',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('staff', 'Staff'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AddField(
            model_name='meter',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
