# Generated by Django 5.1.2 on 2025-04-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0021_remove_meter_owner_alter_meter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['created_at'], 'verbose_name': 'Meter', 'verbose_name_plural': 'Meters'},
        ),
    ]
