# Generated by Django 5.1.2 on 2025-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0022_alter_meter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('client', 'Client')], default='client', max_length=10),
        ),
    ]
