# Generated by Django 5.1.2 on 2025-04-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0023_alter_meter_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='status',
            new_name='role',
        ),
    ]
