# Generated by Django 5.1.2 on 2025-04-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0024_rename_status_meter_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='energy_meter_app.meter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
