# Generated by Django 5.1.2 on 2025-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter_app', '0025_powerpurchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerpurchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Power Purchase', 'verbose_name_plural': 'Power Purchases'},
        ),
        migrations.RenameField(
            model_name='powerpurchase',
            old_name='created_at',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='powerpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
